name: Upload to PDS

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.x

      - name: Upload to PDS
        env:
          PDS_URL: ${{ secrets.PDS_URL }}
          IDENTIFIER: ${{ secrets.IDENTIFIER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          COLLECTION: ${{ secrets.COLLECTION }}
          RKEY: ${{ secrets.RKEY }}
          MARKDOWN_PATH: ${{ secrets.MARKDOWN_PATH }}
        run: deno task upload
